[build-system]
requires = ["setuptools>=61.0", "cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name="gwplot"
version='0.0.1'
description="Visualise genomics data fast"
requires-python='>=3.8'
readme="README.md"
authors=[
    { name = "Kez Cleal", email = "clealk@cardiff.ac.uk" }
]
classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools]
py-modules=["_custom_build"]
packages=["gwplot"]

[tool.setuptools.cmdclass]
build_py="_custom_build.build_py"

[project.urls]
Repository="https://github.com/kcleal/gwplot"

[project.optional-dependencies]
test = ["numpy", "pillow"]