"""Type stubs for gwplot.interface (Cython extension)."""
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

__all__ = ["Gw", "GwPalette"]


class GwPalette:
    BACKGROUND: int
    BACKGROUND_TILED: int
    BACKGROUND_MENU: int
    NORMAL_READ: int
    DELETION: int
    DUPLICATION: int
    INVERSION_FORWARD: int
    INVERSION_REVERSE: int
    TRANSLOCATION: int
    INSERTION: int
    SOFT_CLIP: int
    NUCLEOTIDE_A: int
    NUCLEOTIDE_T: int
    NUCLEOTIDE_C: int
    NUCLEOTIDE_G: int
    NUCLEOTIDE_N: int
    COVERAGE: int
    TRACK: int
    NORMAL_READ_MQ0: int
    DELETION_MQ0: int
    DUPLICATION_MQ0: int
    INVERSION_FORWARD_MQ0: int
    INVERSION_REVERSE_MQ0: int
    TRANSLOCATION_MQ0: int
    SOFT_CLIP_MQ0: int
    BIGWIG: int
    REGION_OF_INTEREST: int
    MATE_PRIMARY: int
    MATE_SECONDARY: int
    MATE_UNMAPPED: int
    SPLIT_READ: int
    SELECTED_ELEMENT: int
    LINE_JOINS: int
    LINE_COVERAGE: int
    LINE_LIGHT_JOINS: int
    LINE_GTF_JOINS: int
    LINE_LABEL: int
    LINE_BRIGHT: int
    LINE_GAP: int
    TEXT_DELETION: int
    TEXT_INSERTION: int
    TEXT_LABELS: int
    TEXT_BACKGROUND: int
    MARKERS: int
    METHYLATED_C: int
    HYDROXYMETHYLATED_C: int
    OTHER_MODIFICATION: int
    CODON_START: int
    CODON_STOP: int
    CODON_OTHER: int
    CODON_SELECTED_BG: int


class Gw:
    raster_surface_created: bool

    def __init__(self, reference: str, ini: str | None = None, **kwargs: Any) -> None: ...
    def __repr__(self) -> str: ...
    def __enter__(self) -> Gw: ...
    def __exit__(self, exc_type: Optional[type], exc_val: Optional[Exception], exc_tb: Optional[Any]) -> None: ...
    @staticmethod
    def onlineGenomeTags() -> Dict[str, str]: ...
    @staticmethod
    def online_genome_tags() -> Dict[str, str]: ...
    def glfw_init(self) -> Gw: ...
    def flush_log(self) -> str: ...
    @property
    def selected_align(self) -> str: ...
    def clear_selected_align(self) -> None: ...
    @property
    def selected_intron(self) -> str: ...
    def clear_selected_intron(self) -> None: ...
    @property
    def selected_feature(self) -> str: ...
    def clear_selected_feature(self) -> None: ...
    @property
    def clear_buffer(self) -> bool: ...
    def set_clear_buffer(self, state: bool) -> None: ...
    @property
    def redraw(self) -> bool: ...
    def set_redraw(self, state: bool) -> None: ...
    def mouse_event(self, x_pos: float, y_pos: float, button: int, action: int) -> None: ...
    @property
    def canvas_width(self) -> int: ...
    def set_canvas_width(self, width: int) -> Gw: ...
    @property
    def canvas_height(self) -> int: ...
    def set_canvas_height(self, height: int) -> Gw: ...
    @property
    def canvas_size(self) -> Tuple[int, int]: ...
    def set_canvas_size(self, width: int, height: int) -> Gw: ...
    @property
    def font_size(self) -> int: ...
    def set_font_size(self, size: int) -> Gw: ...
    @property
    def font_name(self) -> str: ...
    def set_font_name(self, name: str) -> Gw: ...
    @property
    def theme(self) -> str: ...
    def set_theme(self, theme_name: str) -> Gw: ...
    def apply_theme(self, theme_dict: Dict[int, Tuple[int, int, int, int]]) -> Gw: ...
    def load_theme_from_json(self, filepath: str) -> Gw: ...
    def save_theme_to_json(self, filepath: str) -> Gw: ...
    @property
    def ini_path(self) -> str: ...
    @property
    def threads(self) -> int: ...
    def set_threads(self, threads: int) -> Gw: ...
    @property
    def indel_length(self) -> int: ...
    def set_indel_length(self, indel_length: int) -> Gw: ...
    @property
    def ylim(self) -> int: ...
    def set_ylim(self, ylim: int) -> Gw: ...
    @property
    def sam_max_y(self) -> int: ...
    @property
    def vscroll(self) -> int: ...
    def set_vscroll(self, value: int) -> Gw: ...
    @property
    def pileup_depth(self) -> int: ...
    @property
    def split_view_size(self) -> int: ...
    def set_split_view_size(self, split_view_size: int) -> Gw: ...
    @property
    def pad(self) -> int: ...
    def set_pad(self, pad: int) -> Gw: ...
    @property
    def max_coverage(self) -> int: ...
    def set_max_coverage(self, max_coverage: int) -> Gw: ...
    @property
    def max_tlen(self) -> int: ...
    def set_max_tlen(self, max_tlen: int) -> Gw: ...
    @property
    def log2_cov(self) -> bool: ...
    def set_log2_cov(self, log2_cov: bool) -> Gw: ...
    @property
    def mods(self) -> bool: ...
    @property
    def draw_line(self) -> bool: ...
    @property
    def min_junction_reads(self) -> int: ...
    @property
    def tlen_yscale(self) -> bool: ...
    def set_tlen_yscale(self, tlen_yscale: bool) -> Gw: ...
    @property
    def expand_tracks(self) -> bool: ...
    def set_expand_tracks(self, expand_tracks: bool) -> Gw: ...
    @property
    def data_labels(self) -> bool: ...
    def set_data_labels(self, data_labels: bool) -> Gw: ...
    @property
    def vcf_as_tracks(self) -> bool: ...
    def set_vcf_as_tracks(self, vcf_as_tracks: bool) -> Gw: ...
    @property
    def sv_arcs(self) -> bool: ...
    def set_sv_arcs(self, sv_arcs: bool) -> Gw: ...
    @property
    def scroll_speed(self) -> float: ...
    def set_scroll_speed(self, scroll_speed: float) -> Gw: ...
    @property
    def tab_track_height(self) -> float: ...
    def set_tab_track_height(self, tab_track_height: float) -> Gw: ...
    def set_track_height(self, index: int, height: float) -> Gw: ...
    def get_tracks(self) -> List[Dict[str, Any]]: ...
    def get_viewport(self) -> Dict[str, Any]: ...
    @property
    def translation(self) -> bool: ...
    @property
    def translation_frame(self) -> int: ...
    @property
    def translation_strand(self) -> str: ...
    def set_translation(self, enabled: bool) -> Gw: ...
    def set_translation_frame(self, frame: int) -> Gw: ...
    def set_translation_strand(self, strand: str) -> Gw: ...
    def set_translation_code(self, code: int) -> Gw: ...
    @property
    def start_index(self) -> int: ...
    def set_start_index(self, start_index: int) -> Gw: ...
    @property
    def soft_clip_threshold(self) -> int: ...
    def set_soft_clip_threshold(self, soft_clip_threshold: int) -> Gw: ...
    @property
    def edge_highlights(self) -> int: ...
    def set_edge_highlights(self, edge_highlights: int) -> Gw: ...
    @property
    def small_indel_threshold(self) -> int: ...
    def set_small_indel_threshold(self, small_indel_threshold: int) -> Gw: ...
    @property
    def snp_threshold(self) -> int: ...
    def set_snp_threshold(self, snp_threshold: int) -> Gw: ...
    @property
    def variant_distance(self) -> int: ...
    def set_variant_distance(self, variant_distance: int) -> Gw: ...
    @property
    def low_memory(self) -> int: ...
    def set_low_memory(self, low_memory: int) -> Gw: ...
    def set_image_number(self, x: int, y: int) -> Gw: ...
    def set_paint_ARBG(self, paint_enum: int, a: int, r: int, g: int, b: int) -> Gw: ...
    def set_paint_ARGB(self, paint_enum: int, a: int, r: int, g: int, b: int) -> Gw: ...
    def set_active_region_index(self, index: int) -> Gw: ...
    def clear_alignments(self) -> None: ...
    def clear_regions(self) -> None: ...
    def clear(self) -> None: ...
    def add_bam(self, path: str) -> Gw: ...
    def add_pysam_alignments(self, pysam_alignments: List[Any], col: int = -1, row: int = -1) -> Gw: ...
    def remove_bam(self, index: int) -> Gw: ...
    def add_track(self, path: str, vcf_as_track: bool = True, bed_as_track: bool = True) -> Gw: ...
    def remove_track(self, index: int) -> Gw: ...
    def add_region(self, chrom: str, start: int, end: int, marker_start: int = -1, marker_end: int = -1) -> Gw: ...
    def remove_region(self, index: int) -> Gw: ...
    def add_marker(self, chrom: str, pos: int, end: int = -1) -> Gw: ...
    def remove_marker(self, chrom: str, pos: int) -> Gw: ...
    def clear_markers(self) -> Gw: ...
    @property
    def markers(self) -> List[Tuple[str, int, int]]: ...
    def apply_command(self, command: str) -> Gw: ...
    def key_press(self, key: int, scancode: int, action: int, mods: int) -> None: ...
    def make_raster_surface(self, width: int = -1, height: int = -1) -> Gw: ...
    def save_png(self, path: str) -> Gw: ...
    def save_pdf(self, path: str) -> Gw: ...
    def save_svg(self, path: str) -> Gw: ...
    def draw(self, clear_buffer: bool = False) -> Gw: ...
    def draw_image(self) -> Any: ...
    def show(self) -> None: ...
    def view_region(self, chrom: str, start: int, end: int) -> Gw: ...
    def encode_as_png(self, compression_level: int = 6) -> Optional[bytes]: ...
    def encode_as_jpeg(self, quality: int = 80) -> Optional[bytes]: ...
    @property
    def __array_interface__(self) -> Optional[Dict[str, Any]]: ...
    def array(self) -> Optional[np.ndarray]: ...
