#!/bin/bash

echo "STARTING MANYLINUX-DEPS"

yum -y groupinstall "Development Tools"
yum -y install glibc-devel
yum -y install gcc gcc-c++ autoconf openssl-devel libffi libffi-devel zlib-devel \
    bzip2-devel bzip2-libs xz-devel xz-libs libffi atlas-devel libjpeg-devel curl-devel curl \
    cmake xorg-x11-server-Xorg xorg-x11-xauth xorg-x11-apps libXcursor-devel libXi-devel libXinerama-devel \
    wayland-devel libxkbcommon-devel wayland-protocols-devel libXrandr libXrandr-devel libssh2 libs3 \
    extra-cmake-modules
yum -y install fontconfig-devel libpng-devel librsvg2-devel libX11-devel mesa-libEGL-devel mesa-libGLES-devel \
    freetype-devel libuuid-devel glfw


#curl -L -o glfw-3.3.8.zip https://github.com/glfw/glfw/releases/download/3.3.8/glfw-3.3.8.zip
#unzip glfw-3.3.8.zip && cd glfw-3.3.8
#cmake -S . -B build && cd build && make
#cp ./src/libglfw3.a /usr/local/lib && cp ./src/libglfw3.a /usr/local/lib/libglfw.a
#cd ../ && ls
#cp -rf include/GLFW /usr/local/include
#ls /usr/local/include/
#ls /usr/local/include/GLFW/
#cd ../

git clone --depth 1 https://github.com/ebiggers/libdeflate.git && \
    cd libdeflate && CFLAGS+=' -fPIC -O3 ' cmake -B build && CFLAGS+=' -fPIC -O3 ' cmake --build build
cp build/libdeflate.a /usr/local/lib && cp libdeflate.h /usr/local/include
cd ../


curl -L -o htslib.tar.bz2 https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2
ls -lh
tar -xvf htslib.tar.bz2
mv htslib-1.17 htslib && rm htslib.tar.bz2
cd htslib
./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2 --with-libdeflate
make -j3 && make install
cd ../


pwd
ls

cd gw
make prep
make shared -j3
cp lib/libgw/out/* /usr/local/lib/

echo "MANYLINUX-DEPS DONE"
