#!/bin/bash

echo "STARTING MANYLINUX-DEPS"

dnf install -y epel-release

dnf -y groupinstall "Development Tools"

dnf -y install gcc gcc-c++ autoconf openssl-devel libffi libffi-devel zlib-devel \
    bzip2-devel bzip2-libs xz-devel xz-libs libffi atlas-devel curl-devel \
    cmake xorg-x11-server-Xorg xorg-x11-xauth xorg-x11-apps libXcursor-devel libXi-devel libXinerama-devel \
    libxkbcommon-devel libXrandr libXrandr-devel libssh2 libs3 \
    extra-cmake-modules

dnf install -y fontconfig-devel freetype-devel libjpeg-turbo-devel libpng-devel xz-devel \
    libuuid-devel librsvg2-devel \
    libX11-devel mesa-libEGL-devel mesa-libGLES-devel \
    wayland-devel wayland-protocols-devel \
    glfw-devel

#curl -L -o glfw-3.4.zip https://github.com/glfw/glfw/releases/download/3.4/glfw-3.4.zip
#unzip glfw-3.4.zip > /dev/null 2>&1
#cd glfw-3.4
#cmake -S . -B build && cd build && make
#cp ./src/libglfw3.a /usr/local/lib && cp ./src/libglfw3.a /usr/local/lib/libglfw.a
#cd ../ && ls
#cp -rf include/GLFW /usr/local/include
#ls /usr/local/include/
#ls /usr/local/include/GLFW/
#cd ../
#
git clone --depth 1 https://github.com/ebiggers/libdeflate.git && \
    cd libdeflate && CFLAGS+=' -fPIC -O3 ' cmake -B build && CFLAGS+=' -fPIC -O3 ' cmake --build build
cp build/libdeflate.a /usr/local/lib && cp libdeflate.h /usr/local/include
cd ../


curl -L -o htslib.tar.bz2 https://github.com/samtools/htslib/releases/download/1.21/htslib-1.21.tar.bz2
ls -lh
tar -xvf htslib.tar.bz2 > /dev/null 2>&1
mv htslib-1.21 htslib && rm htslib.tar.bz2
cd htslib
./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2 --with-libdeflate
make -j3 && make install
cd ../


pwd
ls

cd ./gw
make prep > /dev/null 2>&1
make shared -j3
cp libgw/*.* /usr/local/lib
cp libgw/libskia.a ../gwplot/
cd ../
cp -rf libgw/GW /usr/local/include
ls -lh /usr/local/lib/libgw*
ls -lh /usr/local/lib/libskia.a
ls -lh /usr/local/include/GW
pwd
ls -lh ./gwplot

echo "MANYLINUX-DEPS DONE"
