#!/bin/bash
# Install build dependencies. Run from inside dysgu folder

echo "STARTING MANYLINUX-DEPS"

yum -y install gcc gcc-c++ wget autoconf openssl-devel libffi libffi-devel zlib-devel \
    bzip2-devel bzip2-libs xz-devel xz-libs libffi atlas-devel libjpeg-devel libssh2 curl-devel curl \
    cmake libs3 xorg-x11-server-Xorg xorg-x11-xauth xorg-x11-apps libXcursor-devel libXi-devel libXinerama-devel \
    wayland-devel libxkbcommon-devel wayland-protocols-devel extra-cmake-modules libXrandr-devel


wget https://github.com/glfw/glfw/releases/download/3.4/glfw-3.4.zip && unzip glfw-3.4.zip && cd glfw-3.4
cmake -S . -B build && cd build && make
ls && cp libglfw*a /usr/local/lib
cd ../ && cp -rf include/GLFW3 /usr/local/include


git clone --depth 1 https://github.com/ebiggers/libdeflate.git && \
    cd libdeflate && CFLAGS+=' -fPIC -O3 ' cmake -B build && CFLAGS+=' -fPIC -O3 ' cmake --build build && \
    cp build/libdeflate.a /usr/local/lib && cp libdeflate.h /usr/local/include && cd ../

cd ./dysgu
wget -O htslib.tar.bz2 https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2
ls -lh
tar -xvf htslib.tar.bz2
mv htslib-1.17 htslib && rm htslib.tar.bz2
cd htslib

#autoheader
#autoconf
./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2 --with-libdeflate
make
ls
cp -rf ./htslib ../include
cp -rf ./cram ../include
cp libhts.so ../gwplot/

echo "MANYLINUX-DEPS DONE"
