#!/bin/bash

echo "Starting in $(pwd)"
echo "Contents of {wheel}: "
ls -l {wheel}
cp -rf {wheel} .

echo "Contents of current directory:"
ls -l
python -m wheel unpack {wheel} --dest wheel_contents

echo "Wheel contents:"
ls -Ra wheel_contents

echo "Running ldd..."
ldd $(find wheel_contents -name "interface.*.so")

echo "Running objdump..."
objdump -p $(find wheel_contents -name "interface.*.so") | grep NEEDED

echo "Installing wheel..."
pip install {wheel}
python -c "import gwplot"