#!/bin/bash

echo "STARTING OSX-DEPS"

wget https://github.com/glfw/glfw/releases/download/3.4/glfw-3.4.bin.MACOS.zip
unzip glfw-3.4.bin.MACOS.zip && cd glfw-3.4.bin.MACOS/lib-universal
cp libglfw3.a /usr/local/lib && cd ../
ls; ls include; cp -rf include/GLFW* /usr/local/include && cd ../

git clone --depth 1 https://github.com/ebiggers/libdeflate.git && \
    cd libdeflate && CFLAGS+=' -fPIC -O3 ' cmake -B build && CFLAGS+=' -fPIC -O3 ' cmake --build build && \
    cp build/libdeflate.a /usr/local/lib && cp libdeflate.h /usr/local/include && cd ../

wget -O htslib.tar.bz2 https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2
ls -lh
tar -xvf htslib.tar.bz2
mv htslib-1.17 htslib && rm htslib.tar.bz2
cd htslib

CPPFLAGS+="-I./include" LDFLAGS+="-L." ./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2 --with-libdeflate
make
ls
cp -rf ./htslib ../include
cp -rf ./cram ../include
cp ./libhts.3.dylib ../gwplot/

echo "OSX-DEPS DONE"
