#!/bin/bash

echo "STARTING OSX-DEPS"

wget https://github.com/glfw/glfw/releases/download/3.4/glfw-3.4.bin.MACOS.zip
unzip glfw-3.4.bin.MACOS.zip && cd glfw-3.4.bin.MACOS/lib-universal
cp libglfw3.a /usr/local/lib
cp libglfw3.a /usr/local/lib/libglfw.a
cd ../
cp -rf include/GLFW* /usr/local/include
cd ../

git clone --depth 1 https://github.com/ebiggers/libdeflate.git && \
    cd libdeflate && CFLAGS+=' -fPIC -O3 ' cmake -B build && CFLAGS+=' -fPIC -O3 ' cmake --build build && \
    cp build/libdeflate.a /usr/local/lib && cp libdeflate.h /usr/local/include
cd ../

wget -O htslib.tar.bz2 https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2
ls -lh
tar -xvf htslib.tar.bz2
mv htslib-1.17 htslib && rm htslib.tar.bz2

cd htslib
./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2 --with-libdeflate
make && make install
cd ../




#echo "STARTING OSX-DEPS"

#SCRIPT=$(realpath "$0")
#SCRIPTPATH=$(dirname "$SCRIPT")
#echo "BUILDING IN: " ${SCRIPTPATH}
#D=${SCRIPTPATH}/build_gwplot
#cd ${SCRIPTPATH}
#mkdir -p build_gwplot && cd build_gwplot

#GLFW
#wget https://github.com/glfw/glfw/releases/download/3.4/glfw-3.4.bin.MACOS.zip
#unzip glfw-3.4.bin.MACOS.zip && rm glfw-3.4.bin.MACOS.zip
#cp glfw-3.4.bin.MACOS/lib-universal/libglfw3.a ${D}
#cp -rf glfw-3.4.bin.MACOS/include/GLFW ${D}
#ln -s ${D}/libglfw.a ${D}/libglfw3.a
#rm -rf glfw-3.4.bin.MACOS

#Libdeflate
#git clone --depth 1 https://github.com/ebiggers/libdeflate.git && \
#    cd libdeflate && CFLAGS+=' -fPIC -O3 ' cmake -B build && CFLAGS+=' -fPIC -O3 ' cmake --build build
#cp build/libdeflate.a ${D} && cp libdeflate.h ${D}
#cd ${D}
#rm -rf libdeflate

#Htslib
#wget -O htslib.tar.bz2 https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2
#tar -xvf htslib.tar.bz2
#rm htslib.tar.bz2
#cd htslib-1.17
#CPPFLAGS+="-I../" LFDLAGS+="-L../" ./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2 # --with-libdeflate
#make -j3
#makes install
#cp libhts.* ${D}
#cp libhts.dylib libhts.so ../../../gwplot  # package shared lib
#cp -rf htslib ${D}
#cp -rf cram ${D}
#cd ${D}
#rm -rf htslib-1.17

#build GW
cd ../gw
make prep
CPPFLAGS+="-I/usr/local/include" LDFLAGS+="-L/usr/local/lib" make shared -j3
cp lib/libgw/out/* ../gwplot


echo "OSX-DEPS DONE"
