#!/bin/bash

echo "STARTING OSX-RUN-DEPS"

mkdir -p build && cd build

git clone --depth 1 https://github.com/ebiggers/libdeflate.git && \
    cd libdeflate && CFLAGS+=' -fPIC -O3 ' cmake -B build && CFLAGS+=' -fPIC -O3 ' cmake --build build

cp build/libdeflate.a ../ && cp libdeflate.h ../ && cd ../

wget -O htslib.tar.bz2 https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2
ls -lh
tar -xvf htslib.tar.bz2
mv htslib-1.17 htslib && rm htslib.tar.bz2

cd htslib
CPPFLAGS+="-I./include" ./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2 --with-libdeflate
make # && make install && cd ../
cp libhts*dylib ../
cp -rf htslib ../
cp -rf cram ../

echo "OSX-RUN-DEPS DONE"
