#!/bin/bash

echo "STARTING OSX-DEPS"

SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
echo "BUILDING IN: " ${SCRIPTPATH}
D=${SCRIPTPATH}/build_gwplot
cd ${SCRIPTPATH}
mkdir -p build_gwplot && cd build_gwplot

#GLFW
wget https://github.com/glfw/glfw/releases/download/3.4/glfw-3.4.bin.MACOS.zip
unzip glfw-3.4.bin.MACOS.zip && rm glfw-3.4.bin.MACOS.zip
cp glfw-3.4.bin.MACOS/lib-universal/libglfw3.a ${D}
cp -rf glfw-3.4.bin.MACOS/include/GLFW ${D}
ln -s ${D}/libglfw.a ${D}/libglfw3.a
rm -rf glfw-3.4.bin.MACOS

#Libdeflate
git clone --depth 1 https://github.com/ebiggers/libdeflate.git && \
    cd libdeflate && CFLAGS+=' -fPIC -O3 ' cmake -B build && CFLAGS+=' -fPIC -O3 ' cmake --build build
cp build/libdeflate.a ${D} && cp libdeflate.h ${D}
cd ${D}
rm -rf libdeflate

#Htslib
wget -O htslib.tar.bz2 https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2
tar -xvf htslib.tar.bz2
rm htslib.tar.bz2
cd htslib-1.17
CPPFLAGS+="-I../" LFDLAGS+="-L../" ./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2 --with-libdeflate
make -j3
cp libhts*dylib libhts*so ${D} #../../../gwplot  # package shared lib
cp -rf htslib ${D}
cp -rf cram ${D}
cd ${D}
rm -rf htslib-1.17

#build GW
cd ../../gw
make prep
CPPFLAGS+="-I../ci/buid_gwplot/" LFDLAGS+="-L../ci/buid_gwplot/ -L../gwplot" make shared -j3
cp lib/libgw/out/* ../gwplot


echo "OSX-DEPS DONE"
