#!/bin/bash

echo "STARTING OSX-DEPS"

#wget https://github.com/glfw/glfw/releases/download/3.4/glfw-3.4.bin.MACOS.zip
#unzip glfw-3.4.bin.MACOS.zip && cd glfw-3.4.bin.MACOS/lib-universal
#cp libglfw3.a /usr/local/lib
#cp libglfw3.a /usr/local/lib/libglfw.a
#cd ../
#cp -rf include/GLFW* /usr/local/include
#cd ../
PREFIX=$(brew --prefix)
export CPPFLAGS="-I${PREFIX}/include"
export LDFLAGS="-L${PREFIX}/lib"
export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig"

#git clone --depth 1 https://github.com/ebiggers/libdeflate.git && \
#    cd libdeflate && CFLAGS+=' -fPIC -O3 ' cmake -B build && CFLAGS+=' -fPIC -O3 ' cmake --build build && \
#    #cp build/libdeflate.a /usr/local/lib && cp libdeflate.h /usr/local/include
#    cp build/libdeflate.a "${PREFIX}/lib"
#    cp libdeflate.h "${PREFIX}/include"
#cd ../

wget -O htslib.tar.bz2 https://github.com/samtools/htslib/releases/download/1.21/htslib-1.21.tar.bz2
ls -lh
tar -xvf htslib.tar.bz2
mv htslib-1.21 htslib && rm htslib.tar.bz2

cd htslib
./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2 --with-libdeflate --prefix="${PREFIX}"
make && make install
cd ../

cd ./gw
make prep
#CPPFLAGS+="-I/usr/local/include" LDFLAGS+="-L/usr/local/lib" make shared -j3
#cp lib/libgw/* /usr/local/lib/
make shared -j3

ls $PREFIX/lib/hts*
ls $PREFIX/lib/libglfw*
ls $PREFIX/include/GLFW*

echo "OSX-DEPS DONE"
