name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    env:
      PREFIX: "/usr/local/"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-11]

    steps:
      - uses: actions/checkout@v4  # checkout gwplot
      - run: ls; pwd; cd _gw; ls; git fetch; git branch; git checkout gw_dev; cd ../  # checkout gw_dev

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.0
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"
          CIBW_SKIP: "*-win32 *-manylinux_i686 pp* cp311-macosx* *musl* "
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_LINUX: "auto"
          CIBW_BEFORE_ALL_MACOS: bash ci/osx-deps
          CIBW_BEFORE_ALL_LINUX: bash ci/manylinux-deps
          CIBW_BEFORE_BUILD: pip install -r requirements.txt
          CIBW_TEST_COMMAND: dysgu test
          
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
