name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    env:
      PREFIX: "/usr/local/"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-11]

    steps:
      - uses: actions/checkout@v4  # checkout gwplot
        with:
          fetch-depth: 0
          submodules: recursive
      - run: ls; pwd; cd gw; ls; git branch; git remote show origin; git fetch origin; git switch gw_dev; cd ../  # checkout gw_dev

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.0
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"
          CIBW_SKIP: "*-win32 *-manylinux_i686 pp* *musl* "
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=11.0
          CIBW_ARCHS_LINUX: "auto"
          CIBW_BEFORE_ALL_MACOS: bash ci/osx-deps; pwd; ls
          CIBW_BEFORE_ALL_LINUX: bash ci/manylinux-deps
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: ""
          CIBW_TEST_COMMAND: python -m unittest

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
