name: Build manylinux wheels

on: workflow_dispatch

jobs:
  build-manylinux-wheels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BUILD: "cp310-manylinux* cp311-manylinux* cp312-manylinux* cp313-manylinux*"

          CIBW_BEFORE_ALL_LINUX: |
            export OLD_SKIA=1
            export BUILD_GLFW=1
            export BUILD_FREETYPE=0
            export CPPFLAGS="-I/usr/local/include ${CPPFLAGS:-}"
            export LDFLAGS="-L/usr/local/lib ${LDFLAGS:-}"
            bash ci/manylinux-build-deps

          CIBW_BEFORE_BUILD_LINUX: |
            python -m pip install numpy>=1.19.3 "cython>=3.0.0,<3.1"
            python -m pip install --no-binary=pysam --force-reinstall --no-cache-dir pysam>=0.23.0

          CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel -v repair -w {dest_dir} {wheel}"
          CIBW_TEST_COMMAND: bash {package}/ci/manylinux-test {wheel}

      - uses: actions/upload-artifact@v4
        with:
          name: wheels_intel_manylinux
          path: ./wheelhouse/*.whl