name: Build manylinux wheels

on: workflow_dispatch

jobs:
  build-manylinux-wheels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS: x86_64
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"

          CIBW_ENVIRONMENT: |
            CPPFLAGS="-I/usr/local/include"
            LDFLAGS="-L/usr/local/lib"

          CIBW_BEFORE_ALL_LINUX: bash ci/manylinux-build-deps
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel -v repair -w {dest_dir} {wheel}"
          CIBW_TEST_COMMAND: |
            pwd
            ls {project}/dist
            cp {project}/dist/gwplot*.whl .
            
            python -m wheel unpack gwplot*.whl --dest wheel_contents
            echo "Unpacked wheel contents:"
            ls -Ra wheel_contents
            
            echo "Checking interface.so dependencies:"
            ldd wheel_contents/gwplot-*/gwplot/interface.*.so
            objdump -p wheel_contents/gwplot-*/gwplot/interface.*.so | grep NEEDED
            
            echo "Checking libgw dependencies:"
            ldd wheel_contents/gwplot-*/gwplot.libs/libgw.so*
            objdump -p wheel_contents/gwplot-*/gwplot.libs/libgw.so* | grep NEEDED
            
            python -m pip install gwplot*.whl
            python -c "import gwplot"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels_intel_macOS_manylinux
          path: ./wheelhouse/*.whl